services:
  censyssummarizationfrontend:
    image: censyssummarizationfrontend
    build:
      context: frontend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:80
